services:
  vaultwarden:
    image: vaultwarden/server:1.37.4-alpine
    container_name: vaultwarden
    env_file:
      - .env
    environment:
      # Vaultwarden configuration
      SIGNUPS_ALLOWED: "false"
      INVITATIONS_ALLOWED: "false"
      DOMAIN: "https://vaultwarden.vaultwarden.orb.local"
      # Logging configuration
      LOG_FILE: "/data/vaultwarden.log"
      LOG_LEVEL: "warn"
      EXTENDED_LOGGING: "true"
      # Admin token
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
      # Timezone configuration
      TZ: "Europe/Paris"
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8080:80"
