global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  cloudflare:
    acme:
      email: "michel_marcotte@orange.fr"
      storage: "/var/traefik/certs/cloudflare-acme.json"
      # caServer: "https://acme-v02.api.letsencrypt.org/directory" # Production server
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory" # Staging server
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: "10s"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
